version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for client.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
