repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.11.0
    hooks:
      - id: eslint
        name: ESLint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts, *.tsx
        types: [file]
        entry: eslint --fix .
        additional_dependencies:
          - "@next/eslint-plugin-next@latest"
          - "@typescript-eslint/eslint-plugin@latest"
          - "@typescript-eslint/parser@latest"
          - eslint@latest
          - eslint-config-next@latest
          - eslint-config-prettier@latest
          - eslint-import-resolver-typescript@latest
          - eslint-plugin-eslint-comments@latest
          - eslint-plugin-import@latest
          - eslint-plugin-prettier@latest
          - eslint-plugin-react@latest
          - eslint-plugin-react-hooks@latest
          - eslint-plugin-sonarjs@latest
          - eslint-plugin-unicorn@latest
          - prettier@latest
          - typescript@latest
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        name: Prettier
        entry: prettier --write --list-different .
        files: "\\.(graphql|graphqls|json|md|js|jsx|ts|tsx|yaml|yml|css|less|scss)$"
