repos:
  - repo: local
    hooks:
      - id: make-fmt
        name: Make fmt
        entry: bash -c "cd server && make ci"
        language: system
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.8.0
    hooks:
      - id: eslint
        name: ESLint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        entry: bash -c "cd client && eslint src --fix"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        name: Prettier
        entry: prettier --write --list-different
        files: "\\.(graphql|graphqls|json|md|js|jsx|ts|tsx|yaml|yml|css|less|scss)$"
