name: Continuous Integration

on: [push]

jobs:
  client:
    name: client
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "v16.14.0"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install packages
        run: npm ci

      - name: ESLint
        run: npm run lint:fix

      - name: Prettier
        run: npm run fmt:check
