name: Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - go.mod
      - go.sum

  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  server:
    name: server
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'

      - name: Make CI
        run: cd server && make ci

      - name: Exit If Git Diff
        run: |
          chmod +x ./server/scripts/exit_if_diff.sh
          ./server/scripts/exit_if_diff.sh
